<a href="https://colab.research.google.com/github/mcalabresi/Python_for_JS_devs_guide/blob/main/PythonForJSDevelopers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python for JavaScript Developers  

☕ ➡️ 🐍


written by Marcello Calabresi - April 2026

Hello world! This document is a concise guide to get to develop in Python if you have some good grasp of JavaScript (and or TypeScript) in order to get you up and writing Python code in a short time. So Let's start!

First things first: in JavaScript there are many ways of writing code. The same problem may be solved in different ways and in general JS developers don't care much about it. In Python land this is not very well seen and not the norm. There is an opinionated way of writing code and this is contained in a living document called PEP8 which I invite you to read next. https://peps.python.org/pep-0008/

## Comments

In JavaScript we write one line comments with the // and comments on more than one line with the  /*   */ section

JavaScript =>
```js
  // this is a one line comment

  /*
  This is a multiline comment
  which can span multiple lines
  in this case 3 lines
  */

```

In Python we use # symbol for one line comment and '''   ''' for multiline comments.

Python =>

In [ ]:
# hello I am a one line comment

'''
Hello I am a multiline comment
how do you like it
I can now tell you the history of my life
without issues of limit
'''

"""
Also this one works as a multiline comment
but it is preferred to use when you write some documentation as docstring
"""

'\nAlso this one works as a multiline comment\nbut it is preferred to use when you write some documentation as docstring\n'

## How to get some output

In JavaScript our powerful ally is the console.log command, In Python we use the builtin function print(). You can put as many arguments as you like just like console log.
In JavaScript, when you debug a variable you will probably write a console log like this:
JavaScript =>
```
const myVariable = "something";
console.log('myVariable = ', myVariable);
// outputs 'myVariable = something'

```

In Python you can have a very handy shortcut to achieve the same result using fstring

Python =>
```python
my_variable = "something"
print(f'{my_variable=}')
# outputs my_variable = 'something'
```

In [ ]:
print("Hello", "my friend")

my_variable = 'something';
print(f'{my_variable=}')

Hello my friend
my_variable='something'

## Semicolons at the end of a command
You don't need those. In JS they are not also mandatory you may say but it's good programming practice to add a ; at the end of a command. In Python it's the inverse. You can put two commands in a line with a ; but normally you don't do it and put no semicolon

In [ ]:
# two commands in a line
print('hello'); print('world')

# two commands in two lines
print('welcome to this nice')
print('document')

hello
world
welcome to this nice
document


## Variables and constants
In JavaScript you have 3 keywords to define variables and constants

* var ( which you should not use in modern JS btw but it was the only one at the origin)
* let ( for a real variable variable)
* const (for a constant)

Good news: In Python you don't need any of those and there is no builtin check to see if a constant is really a constant

### Naming convention
In JS you would call a variable userPaymentBalance, In Python you would call it instead user_payment_balance ( so in JavaScript you would use the so called 'camel case' while in python you use normally 'snake case'). Beware: in Python you should use 'pascal case' for classes.

in Python also it's good practice to put constants in all uppercase

PI = 3.1415

In [ ]:
from typing import Final


name = "Joe" # we just defined a variable

FAKECONSTANTPI = 3.1415   #this should be a certain well known math constant
FAKECONSTANTPI = 3.15 # no error but it was meant to be a constant!

PI:Final[float] = 3.1415 # you can use static types and define a const like this
# but this is only going to generate a warning in your IDE
PI="Vegeta" #I don't see any error here bro

print(name)
print(PI)

# if you REALLY REALLY need a constant you need to use a tuple
constantPI = (3.1415)
# constantPI[0] = 23 # this will not work

Joe
Vegeta

## Ternary operator (and f-string)

In JavaScript we have


```js
let candies = 20;
const howManyCandiesText =`You have ${candies} ${candies > 1 ? "candies" : "candy"}.`;
console.log(howManyCandiesText);
```

How to do the same in Python? There's of course a different syntax!

In the following example we also take a look at the so-called f-string which is the way to express template literals
```js
let variable = `...some text ${variableToDisplay}`
```
becomes

```python
variable = f" .... some text {variable_to_display}"
```

In [ ]:
candies = 20;
how_many_candies_text = f"You have {candies} {"candies" if candies > 1 else "candy"}."
print(how_many_candies_text)

You have 20 candies.

## For loops using range

In JavaScript we have different ways to make a loop. The most classic one is


```js
for(let i = 0; i<10; i+=1){
  console.log(i)
}
```
This comes from C syntax. There's nothing like this in Python. You need to use range function instead

This is a smart idea, in this way you avoid accessing elements that are not supposed to be accessed. I totally like C syntax but this is much more understandable and modern.

Notice some things in the following example:
* there's no brackets after the for keyword ( this is true also for if and some other statements)
* there's no curly braces in the block that should be run but there is a column
* there is a mandatory indentation for the block

In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9

## Looping through the elements of an array ( list )

What you call arrays in JS they are called lists in Python
In JavaScript you have the "for of" construct. If you use it you are lucky because it's the same for Python except that it is called "for in".

Also notice there is also no array.foreach



```js
const italianCarBrands = ["Ferrari", "Lamborghini", "Fiat","Lancia"];
for( brand of italianCarBrands){
  console.log(`I own a ${brand} car and I like it`);
}
```

In [ ]:
italian_car_brands = ["Ferrari", "Lamborghini", "Fiat","Lancia"]
for brand in italian_car_brands:
  print(f"I own a {brand} car and I like it")

I own a Ferrari car and I like it
I own a Lamborghini car and I like it
I own a Fiat car and I like it
I own a Lancia car and I like it

## JavaScript Objects are called dicts (dictionaries)

There is an important difference: keys in dicts should be strings ( just like in JSON )

```js

const myNewCar = {
  brand: "Ferrari",
  model: "Testarossa",
  year: 1982,
  name: "Reddie"
}

console.log(`I like my ${myNewCar.brand} ${myNewCar["model"]}`);

```
Note well that I used two different ways of accessing an element of my object ( with the . and with the []

In Python we just access with the []

In [ ]:
my_new_car = {
  "brand": "Ferrari",
  "model": "Testarossa",
  "year": 1982,
  "name": "Reddie"
}

print(f"I like my {my_new_car["brand"]} {my_new_car["model"]}")

# getting the keys of a dict and putting them in a list
print(list(my_new_car.keys()))

# getting the values of a dict and putting them in a list
print(list(my_new_car.values()))

# getting a tuple with key and values of a dict and putting them in a list
print(list(my_new_car.items()))

I like my Ferrari Testarossa
['brand', 'model', 'year', 'name']
['Ferrari', 'Testarossa', 1982, 'Reddie']
[('brand', 'Ferrari'), ('model', 'Testarossa'), ('year', 1982), ('name', 'Reddie')]

## Tuples, the immutable data structure

A tuple is like a list but it's immutable, you cannot add or remove any value from it, you cannot modify its values. What do we use it for then ? A classic example is when a function returns multiple values. In this case it puts them into a tuple. You can access the values of a tuple as you would access the values of a list ( with square brackets ). In the example just above the function list.items returns a tuple.

You can create a list from a tuple

In [ ]:

original_carbonara_ingredients = ("pasta","pork cheek","egg yolks", "black pepper", "roman pecorino cheese")

# create a list from a tuple
fakeable_carbonara_ingredients = list(original_carbonara_ingredients)
fakeable_carbonara_ingredients.append("cream") # you can add ingredients

# original_carbonara_ingredients.append("cream") #you get an error if you run this line

print("Fakeable Carbonara Ingredients: ")
for i in fakeable_carbonara_ingredients:
  print(i)

print("\n")

print("Original Carbonara Ingredients: ")
for i in original_carbonara_ingredients:
  print(i)

Fakeable Carbonara Ingredients:
pasta
pork cheek
egg yolks
black pepper
roman pecorino cheese
cream


Original Carbonara Ingredients:
pasta
pork cheek
egg yolks
black pepper
roman pecorino cheese

## Lists, a powerful data type

Lists are indeed one of the most powerful features of Python. Unlike arrays in JS there are many built-in methods that allow us to do very good data manipulation. Remember: List insertion order is important and is kept.

### selecting parts of a string (slicing)

In JavaScript you need to use splice or better toSpliced (for immutability)
[toSplicedReference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSpliced)

```js
const elements=["one","two","three", "four", "five"];
const elements2 = elements.toSpliced(0,4);
const elements3 = elements.toSpliced(4,1);
const elements4 = elements.toSpliced(-1);
console.log(elements2); // ["five"]
console.log(elements3); // ['one', 'two', 'three', 'four']
console.log(elements4); // ['one', 'two', 'three', 'four']

```

in Python instead we will just select what we want in a similar way by using a syntax that you may be familiar with if you ever did an excel macro function.

my_list[k] => get the kth element
my_list[start:end] =>get the elements from start index to end index (not included)
my_list[start:end:step] => get the elements from start index to end index ( not included) using step (if step = 2 take one element and skip the next)
my_list[index1,index2,index3] => get only the elements at the indexes that were referenced  in the square brackets

In [ ]:
elements = ["one","two","three", "four", "five"]
elements2 = elements[4:]
elements3 = elements[0:4] # notice that 4 is not included so we are selecting elements from idx 0 to idx 4
elements4 = elements[0:-1]

print(elements2)
print(elements3)
print(elements4)

['five']
['one', 'two', 'three', 'four']
['one', 'two', 'three', 'four']

To get the length of an array in JS we write

```js
const elements=["one","two","three", "four", "five"];

const elementsLength = elements.length;

```

in Python we use the command len and we pass the list as an argument

In [ ]:
elements = ["one","two","three", "four", "five"]
elements_length = len(elements)
print(elements_length)

5

There are many more interesting methods of the list class that you will surely use like append (equivalent to push), pop, etc

In [ ]:
my_other_list = [1,2,4]

# adding a value
my_other_list.append(3)
print(f'{my_other_list = }')

# removing a value
my_other_list.remove(1)
print(f'{my_other_list = }')

# sorting the values of a list
my_other_list.sort()
print(f'{my_other_list = }')

# copying a list !! important this is a shallow copy, for deep copy... use deepcopy from copy module
my_list_copy = my_other_list.copy()
print(f'{my_list_copy = }')

# reversing a list
my_list_copy.reverse()
print(f'{my_list_copy = }')


# what is the minimum element?
min_element = min(my_other_list)
print(f'{min_element = }')

# what is the maximum element?
max_element = max(my_other_list)
print(f'{max_element = }')

# insert a value at index 1
my_other_list.insert(1,333)
print(f'{my_other_list=}')

# merge two lists into 1 like [...array1,...array2] in js
another_list=[54,34,89]
my_other_list.extend(another_list)
print(f'{my_other_list=}')
# another way to do this is my_other_list = my_other_list + another_list

# how many times the element 333 is present in my_other_list?
nb_333 = my_other_list.count(333)
print(f'{nb_333=}')

#index of 333 ?
print(f'index of 333 is {my_other_list.index(333)}')

my_other_list = [1, 2, 4, 3]
my_other_list = [2, 4, 3]
my_other_list = [2, 3, 4]
my_list_copy = [2, 3, 4]
my_list_copy = [4, 3, 2]
min_element = 2
max_element = 4
my_other_list=[2, 333, 3, 4]
my_other_list=[2, 333, 3, 4, 54, 34, 89]
nb_333=1
index of 333 is 1

## Map, Filter and Reduce

map and filter are built-in functions while reduce comes from a library called functools

In the code below we make use of lambda functions as you may see. These are equivalent to anonymous functions in js

Notice how easy is to use range instead of Array.from , on the other side using map is a little more complicated in Python as you need to cast it to a list

```js
const numbers = Array.from({ length: 10 }, (v, i) => i);
console.log(numbers)
const doubleNumbers = numbers.map(n => 2*n)
console.log(doubleNumbers)

const oddNumbers = numbers.filter(n => n%2 !== 0)

const sumOfOddValues = oddNumbers.reduce((curr,acc)=> curr+acc,0)
```

Another thing to notice is that in Python land you will use == or != and not === or !== as we are used to in JS

In [ ]:
from functools import reduce

numbers = list(range(0,10))
print(numbers)

double_numbers = list(map(lambda x: 2*x, numbers))
print(double_numbers)

odd_numbers = list(filter(lambda x: x%2 != 0,numbers))
print(odd_numbers)

odd_numbers_sum = reduce(lambda curr,acc : curr+acc,odd_numbers,0)
print(odd_numbers_sum)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[1, 3, 5, 7, 9]
25

### List comprehensions
What if we could put map and filter capabilities in the same place and use a nicer syntax? That's what list comprehensions are for!!! Let's use list comprehensions to write the above examples. The important thing is to specify at the beginning what kind of value you want to be mapped and then for which values you want to loop for and in the end we pass an if clause to filter eventual unwanted values.

Once you learn list comprehensions please notice that we can use the same mechanism also for dicts ( dict comprehensions )

In [ ]:
numbers = list(range(0,10))
print(numbers)
# map with list comprehension
double_numbers = [2*x for x in numbers]
print(double_numbers)

# filter with list comprehension
odd_numbers = [x for x in numbers if x%2 !=0]
print(odd_numbers)

# map and filter together in the same list comprehension !
double_odd_numbers =  [2*x for x in numbers if x%2 != 0]
print (double_odd_numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[1, 3, 5, 7, 9]
[2, 6, 10, 14, 18]

## Introducing sets, generators and their comprehensions

### sets

Yes we have sets also in JavaScript, it's like arrays but with unique elements.
Here is some reference => https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

In python we use the curly braces to create a set, like a list but with curly brackets instead of square brackets.
```python
my_set ={1,2,3,4,4}
#notice that the second 4 will not be added because it's already present
```

In [ ]:
my_set ={ 1,2,2,3,4,4,1,5,3}
print(f'{my_set=}')

my_set={1, 2, 3, 4, 5}

### generators

Maybe you heard about generators in JavaScript ( the star functions ), probably not but they are very useful. In a nutshell a generator is a function that returns an iterator. You don't return any value, but you yield it.
I'm not going to explain you what it is a generator, you can find more info here
=> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_generators

Ok so python has got generators too, let's see the syntax and translate a JS generator in Python

JavaScript =>

```js
function* makeRangeIterator(start = 0, end = 10000, step = 1) {
  for (let i = start; i < end; i += step) {
    yield i;
  }
}

const generator = makeRangeIterator(1,10,2)

console.log(generator.next().value) // 1
console.log(generator.next().value) // 3
console.log(generator.next().value) // 5
```
Python =>

In [ ]:
def make_range_iterator(start=0, end=10000, step=1):
  for i in range(start,end,step):
    yield i

generator = make_range_iterator(start=1, end=10, step=2)

print(next(generator))
print(next(generator))
print(next(generator))

1
3
5

We can apply comprehensions to lists, dicts , sets and also generators. You should consider comprehensions as a crazy hybrid between map and filter functions. Some things to consider :
* the enclosing brackets define the type of data you want : square brackets is for lists, curly brackets for sets or dicts, round brackets for generator
* then you define the data that you want : one element normally, except two elements (key and value) for dicts
* the for cycle, specifying where to pick the input data from
* the if condition in case you want to filter out some data (optional)

Here some examples

In [ ]:
# list comprehension
res = [num**2 for num in range(1, 6)]
print(res)

# dict comprehension  (notice the element is expressed in the format key:value)
res = {num: num**3 for num in range(1, 6)}
print(res)

# set comprehension
a = [1, 2, 2, 3, 4, 4, 5, 6, 6, 7]
res = {num for num in a if num % 2 == 0}
print(res)

# generator comprehension
res = (num for num in range(10) if num % 2 == 0)
print(next(res))
print(next(res))
print(next(res))
# we put the other values into a list
print(list(res))

[1, 4, 9, 16, 25]
{1: 1, 2: 8, 3: 27, 4: 64, 5: 125}
{2, 4, 6}
0
2
4
[6, 8]

## OOP in Python

Object Oriented Programming in Python works as in Java, not like in JavaScript!

Quick recap about OOP in JS => In JavaScript OOP is prototypal and there are no "blueprints", just object instances. Keywords like class, constructor, extends are just syntactic sugar to cover quite a convoluted way of achieving OOP (also they were introduced in ES6, before we had only constructor functions). For further reading if you are not familiar with this check this article out => https://dev.to/jps27cse/understanding-javascript-prototypes-a-key-to-mastering-oop-1j1b

let's stick to some ES6 syntax for clarity and let's go on with our comparison in syntax between Python and JS

JS=>
```js
// creation of a Vehicle object

class Vehicle {
  constructor(type){
    this.type = type;
  }
  start(){
    console.log(`${this.type} vehicle starts`);
  }
  stop(){
    console.log(`${this.type} vehicle stops`);
  }
  // this is a special method that will be used when we want to cast this object to a string
  toString(){
    return `I am a ${this.type} vehicle `;
  }
}

const bicycle = new Vehicle('bicycle');
bicycle.start();
bicycle.stop();
// here we are casting bicycle to a string by prepending an empty string
console.log(''+bicycle);

// Car object now inherits from Vehicle object

class Car extends Vehicle {
  constructor(type,numberOfWheels){
    // important we have to invoke the constructor of the parent object
    super(type);
    this.numberOfWheels = numberOfWheels;
  }
  // here we are overloading the original toString method
  toString(){
    return super.toString() + ` and I have ${numberOfWheels} wheels`;
  }
}

const ferrari = new Car('car', 4);
// using the parent methods
ferrari.start();
ferrari.stop();
// now we use the overloaded method
console.log(''+ferrari);

```
Let's implement the same code in Python =>

In [ ]:
class Vehicle:
  # constructor method is __init__ . Remember that the first argument is always self (equivalent to this in JS)
  def __init__(self,type):
    self.type = type

  def start(self):
    print(f"{self.type} vehicle starts")

  def stop(self):
    print(f"{self.type} vehicle stops")
  # method to convert the object to a string
  def __str__(self):
    return f"I am a {self.type} vehicle"

bicycle = Vehicle('bicycle')
bicycle.start()
bicycle.stop()
print(str(bicycle))

class Car(Vehicle):
  def __init__(self,type,number_of_wheels):
    super().__init__(type)
    self.number_of_wheels = number_of_wheels

  def __str__(self):
    return super().__str__() + f" and I have {self.number_of_wheels} wheels"

ferrari = Car('car',4)
ferrari.start()
ferrari.stop()
print(str(ferrari))

bicycle vehicle starts
bicycle vehicle stops
I am a bicycle vehicle
car vehicle starts
car vehicle stops
I am a car vehicle and I have 4 wheels

Now you may be wondering what is all about the special methods starting and ending with two underscores? They are special functions called dunder functions where the word "dunder" stands for "Double UNDERscores" . In Python you can overload many functions to create objects that behave very differently.
Here is a link listing them all => https://www.pythonmorsels.com/every-dunder-method/

🐍 BEWARE:  
* Unlike JS, the first argument of every method of an object MUST always be `self` . You can consider self as the equivalent of JS `this`
* If you want to define class attributes (not tied to the single instance) you need to create them outside the __init__ function and address them as ClassName.attribute

## OOP Getters and setters

In JavaScript there is a nice way to create getters and setters for attributes of an object. Look at the example below
```js
let user = {
  name: "John",
  surname: "Smith",

  // after keywords get or set you should pass a function (method)
  get fullName() {
    return `${this.name} ${this.surname}`;
  },

  set fullName(value) {
    [this.name, this.surname] = value.split(" ");
  }
};

// The setter is executed with the given value. Under the hood we are going to process this value
user.fullName = "Alice Cooper";

console.log(user.fullName) // notice we treat fullName as a new attribute

console.log(user.name); // Alice
console.log(user.surname); // Cooper

```

Getters and setters are there for derived attributes.

Let's see how we can achieve the same in python ( in a pythonic way).
The best way is by using a decorator called @property

Python =>

In [ ]:
class user:
  def __init__(self,name,surname):
    self.name = name
    self.surname = surname
  # with this decorator we define the getter => in Python we are just saying
  # watch out, this is a new attribute of the class
  @property
  def full_name(self):
    return f"{self.name} {self.surname}"

  # here we address the previously defined attribute and we specify the setter
  # as in JS we should provide functions for getter and setter
  @full_name.setter
  def full_name(self,value):
    [self.name,self.surname] = value.split(" ")

# class in Python is just a blueprint , so we should instantiate and initialize
user = user("John","Smith")

# using the setter
user.full_name = "Alice Cooper"

# using the getter
print(user.full_name)

# the setter did the update job for us
print(user.name)
print(user.surname)

Alice Cooper
Alice
Cooper

## Decorators

A decorator in Python is a function (or a class) that wraps another function (input function) to enhance its behaviour without modifying the input function. It is part of so-called metaprogramming and it's a very useful concept that is widely used in many languages.

The most modern syntax is not (yet) part of vanilla JavaScript but it's used extensively in TypeScript and uses the '@' symbol. Read more here => https://medium.com/@artemkhrenov/the-decorator-pattern-in-modern-javascript-adding-functionality-without-breaking-code-b43d9c237047

Notice that in TypeScript decorators are limited to classes, methods and attributes of an object

In [ ]:
# a very simple example of a decorator function

def my_decorator(func):
    def wrapper():
        print("Something is happening before the function is called.")
        func()
        print("Something is happening after the function is called.\n")
    # we take as input a function and we return as output a wrapped function
    return wrapper

@my_decorator
def say_hello():
    print("Hello! I am the output of the original function")

say_hello()

# a very simple example of a decorator class

class deco_class:
  # we need to pass the input function as an attribute, we need to call it later
    def __init__(self, func):
        self.func = func
  # each time we call the decorated input function we execute this code
    def __call__(self):
        print("Hello I am a decorator class")
        # here we execute the input function
        self.func()
        print("Bye\n")

@deco_class
def say_hi():
    print("Hi, I am the output of the original function")

say_hi()

Something is happening before the function is called.
Hello! I am the output of the original function
Something is happening after the function is called.

Hello I am a decorator class
Hi, I am the output of the original function
Bye

## Types as in TypeScript

I don't think I need to explain the advantages of static typing. The Python runtime does not enforce function and variable type annotations. They can be used by third party tools such as type checkers, IDEs, linters, etc.

we need to import a module called typing to define new types

So in general typing in Python is useful just for spotting issues in the IDE, linters and type checkers

In [ ]:
def surface_area_of_cube(edge_length: float) -> str:
    return f"The surface area of the cube is {6 * edge_length ** 2}."

print(surface_area_of_cube(2.3))


from typing import NewType

UserId = NewType('UserId', int)
some_id = UserId(123)
print(some_id)

# notice here the syntax for the parameters and for the return value
def get_user_name(user_id: UserId) -> str:
    if user_id == 42351:
        return "Alice"
    elif user_id == 123:
        return "Bob"
    else:
        return "unknown user"

# passes type checking
user_a = get_user_name(UserId(42351))
print(user_a)

# fails type checking; a string is not a UserId
user_b = get_user_name("hello")
# but still executes
print(user_b)

The surface area of the cube is 31.739999999999995.
123
Alice
unknown user

## Modules and packages

 In JavaScript we have two keywords "import" and "export". In one file we decide what to export and on another file we import what we want. In Python it is slightly different. The keyword export doesn't exist but we still have import. In Python we have these concepts of modules and packages. A module is a set of functions and classes in a file. A package is a a set of modules. Creating a module is straightforward: it is a simple python file. To create a package we have to create a directory and inside we have to place an empty file named "__init__.py". This is enough to let Python know that the content of the folder is a package ( the name of the package will be the name of the folder and the name of the modules will be the name of the files without the .py extension). The syntax to import a certain module is import <module>. We can also import a specific function inside a module
 from <module> import <function_name>
 or we can import a module inside a package like so
 from <package>.<subpackage> import <module>
 or even a function from a module in a subpackage in a package
 from <package>.<subpackage>.<module> import <function>

 There is quite a big freedom. You could also import all the functions from a module like so

 from <module> import *
 where * is the wildcard to import everything. YOU SHOULD NOT DO IT because you can mask some other definitions in standard library or precedingly loaded modules. Also memory-wise it is not a great choice.

 You can read more about this here => https://docs.python.org/3/tutorial/modules.html

 IMPORTANT : In JavaScript you are used to put a path to the library that you are trying to import. This is not the correct approach in Python.
 The correct approach is to add the path to the library you want to import in the Python Path list. You can achieve so by adding the path to the library in the sys.path list

 ```python
# importing module
import sys

# appending a path
sys.path.append(r'C:/Path/To/Your/Library')

 ```

## Rest, spread operators and Python's splat and double splat

remember the ... operator in JS ? This is called spread operator if inside an array or object, rest operator if inside the signature of a function. In Python ... is now the * operator (splat) and it behaves exactly the same. There is also a double splat to spread a dict ** (called also splatty-splat). These two are quite useful when defining functions with variable number of arguments like so

```python
def func(arg1, arg2, *args, **kwargs):
  #notice that in Python the ... is equal to the keyword pass as to say do nothing
  ...

```

In [ ]:
coffees = ['expresso','macchiato', 'cappuccino', 'latte']
softs = ['orange juice', 'almond milk', 'sparkling water']

# spread operator in action
drinks = [*coffees, *softs]
print(drinks)

def order_drinks(number: int, *args, **kwargs):
  print(f"You have ordered {number} drinks")
  print("\nlist of orders:\n")
  for drink in args:
    print(drink)
  for key,value in kwargs.items(): #  Use .items() to unpack key-value pairs
    print(f"{key} = {value}")


order_drinks(2, 'expresso','cappuccino', extra="soy-milk")

['expresso', 'macchiato', 'cappuccino', 'latte', 'orange juice', 'almond milk', 'sparkling water']
You have ordered 2 drinks

list of orders:

expresso
cappuccino
extra = soy-milk

## Walrus operator

This syntax is not present in JavaScript but it's quite interesting and Pythonic.

The Walrus operator, `:=`, allows you to assign a value to a variable within an expression. This can be useful for reducing code redundancy and making your code more concise, especially in `if` and `while` statements where you need to compute a value and then test it.

### Example:

Without the walrus operator:
```python
foods = []
while True:
    food = input("What food do you like? (type 'quit' to exit): ")
    if food == 'quit':
        break
    foods.append(food)
print(f"Your favorite foods are: {foods}")
```

With the walrus operator:
```python
foods = []
while (food := input("What food do you like? (type 'quit' to exit): ")) != 'quit':
    foods.append(food)
print(f"Your favorite foods are: {foods}")
```

In [ ]:
# Example of the Walrus operator in a while loop
foods = []
while (food := input("What food do you like? (type 'quit' to exit): ")) != 'quit':
    foods.append(food)
print(f"Your favorite foods are: {foods}")

# Example of the Walrus operator in an if statement
if (n := len(foods)) > 0:
    print(f"You entered {n} foods.")
else:
    print("You didn't enter any foods.")

What food do you like? (type 'quit' to exit): pasta
What food do you like? (type 'quit' to exit): pizza
What food do you like? (type 'quit' to exit): tortellini
What food do you like? (type 'quit' to exit): quit
Your favorite foods are: ['pasta', 'pizza', 'tortellini']
You entered 3 foods.

## Writing and reading files in Python

If you worked in Node you know you can read or write on the file system using the fs library. Here a quick guide => https://www.w3schools.com/nodejs/nodejs_filesystem.asp

In a nutshell you want to know
* where the file is
* which kind of permissions you need to have to access it ( read-only, update, append, etc)
* the encoding of the file
* if you want to access synchronously or asynchronously

IMPORTANT
In Node you specify the path to the file, In Python you should first change work directory to the folder where the file you want to read or write, only then you can access the file

In Python, file operations are generally performed using the built-in `open()` function. This function returns a file object, which has methods for reading and writing data.

**Basic File Operations:**

*   **Opening a file:** `open(filename, mode)`
    *   `filename`: The path to the file.
    *   `mode`: Specifies how the file will be used. Common modes include:
        *   `'r'` (read): Opens for reading (default). Raises `FileNotFoundError` if the file doesn't exist.
        *   `'w'` (write): Opens for writing. Creates a new file if it doesn't exist, or truncates (empties) the file if it does. **Be careful as it overwrites existing content.**
        *   `'a'` (append): Opens for appending. Creates a new file if it doesn't exist. Writes new data to the end of the file.
        *   `'x'` (create): Creates a new file and opens it for writing. Raises `FileExistsError` if the file already exists.
        *   `'t'` (text): Default mode for text files.
        *   `'b'` (binary): For binary files (e.g., images, executables).

*   **Reading:**
    *   `file_object.read()`: Reads the entire content of the file.
    *   `file_object.readline()`: Reads a single line from the file.
    *   `file_object.readlines()`: Reads all lines into a list of strings.

*   **Writing:**
    *   `file_object.write(string)`: Writes the given string to the file.

*   **Closing a file:** `file_object.close()`
    *   It's crucial to close files to free up system resources and ensure all changes are saved. Failing to close files can lead to data corruption or resource leaks.

### The `with` Statement for File Handling

The `with` statement is the recommended way to handle file operations in Python because it ensures that the file is automatically closed, even if errors occur. This is known as a "context manager."

**Syntax:**
```python
with open(filename, mode) as file_object:
    # Perform read/write operations here
    pass
# The file is automatically closed when exiting the 'with' block
```

Using `with` makes your code safer and cleaner, as you don't have to explicitly call `file_object.close()`.

In [ ]:
# --- Writing to a file ---
file_content = "Hello, Python!\nThis is a test file.\nLearning to write files is fun."

# Using 'w' mode to write (overwrites existing file or creates a new one)
with open('my_example_file.txt', 'w') as f:
    f.write(file_content)
print("Content successfully written to my_example_file.txt")

# --- Appending to a file ---
append_content = "\nThis line was appended."

# Using 'a' mode to append
with open('my_example_file.txt', 'a') as f:
    f.write(append_content)
print("Content successfully appended to my_example_file.txt")

# --- Reading from a file ---
# Using 'r' mode to read
with open('my_example_file.txt', 'r') as f:
    read_data = f.read()
    print("\n--- Content of my_example_file.txt ---")
    print(read_data)

# --- Reading line by line ---
print("\n--- Reading line by line ---")
with open('my_example_file.txt', 'r') as f:
    for line in f:
        print(f"Line: {line.strip()}") # .strip() removes leading/trailing whitespace, including newline characters

Content successfully written to my_example_file.txt
Content successfully appended to my_example_file.txt

--- Content of my_example_file.txt ---
Hello, Python!
This is a test file.
Learning to write files is fun.
This line was appended.

--- Reading line by line ---
Line: Hello, Python!
Line: This is a test file.
Line: Learning to write files is fun.
Line: This line was appended.

## Modules you MUST know of

* random
* re
* sys
* os
* copy
* functools
* numpy
* pandas

### `random`
This module implements pseudo-random number generators for various distributions. It's used for tasks like shuffling lists or picking random elements.

In [ ]:
import random

# Get a random integer between 1 and 10
print(random.randint(1, 10))

# Pick a random element from a list
items = ['apple', 'banana', 'cherry']
print(random.choice(items))

9
apple

### `re` (Regular Expression)
This module provides regular expression operations. It's essential for pattern matching and string manipulation.

In [ ]:
import re

text = "The quick brown fox."
# Search for 'quick' in the text
match = re.search(r'quick', text)
print(match.group() if match else "Not found")

# Replace 'fox' with 'dog'
new_text = re.sub(r'fox', 'dog', text)
print(new_text)

quick
The quick brown dog.

### `sys` (System-specific parameters and functions)
This module provides access to system-specific parameters and functions. It's useful for interacting with the Python interpreter and its environment.

In [ ]:
import sys

# Print the Python version
print(f"Python Version: {sys.version.split(' ')[0]}")

# Print the command line arguments (usually empty in Colab unless passed explicitly)
print(f"Command Line Arguments: {sys.argv}")

# append the current directory in the Python path list, this will not work in a notebook
# current_dir = os.path.dirname(__file__)
# sys.path.append(current_dir)

Python Version: 3.12.13
Command Line Arguments: ['/usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py', '-f', '/root/.local/share/jupyter/runtime/kernel-549d83c0-f886-4a79-ad5e-ac2097e9be7c.json']

### `os` (Miscellaneous operating system interfaces)
This module provides a way of using operating system dependent functionality. It's commonly used for file and directory manipulation.

In [ ]:
import os

# Get the current working directory
print(f"Current working directory: {os.getcwd()}")

# get the current directory of the file, this will not work in a notebook
# current_dir = os.path.dirname(__file__)
# print(f"Current directory of the file: {current_dir}")
current_dir = os.getcwd()

# getting a subpath
img_dir = os.path.join(current_dir, 'images')
print(  f"Subpath: {img_dir}")

# getting an environment variable
API_KEY = os.getenv('API_KEY')
print(f"Environment variable: {API_KEY}")

# List contents of a directory (e.g., current directory)
print(f"Contents of current directory: {os.listdir('.')[:3]}...")

Current working directory: /content
Subpath: /content/images
Environment variable: None
Contents of current directory: ['.config', 'my_example_file.txt', 'sample_data']...

### `copy`
This module provides generic shallow and deep copy operations. It's used to create independent duplicates of mutable objects.

In [ ]:
import copy

original_list = [1, [2, 3], 4]

# Shallow copy: changes to inner lists affect both
shallow_copied_list = copy.copy(original_list)
shallow_copied_list[1][0] = 99
print(f"Original after shallow copy modification: {original_list}")

# Deep copy: fully independent
deep_copied_list = copy.deepcopy(original_list)
deep_copied_list[1][0] = 100
print(f"Original after deep copy modification: {original_list}")

Original after shallow copy modification: [1, [99, 3], 4]
Original after deep copy modification: [1, [99, 3], 4]

### `functools`
This module provides higher-order functions and operations on callable objects. It's useful for function decorators and partial application.

In [ ]:
import functools

# Use functools.partial to create a new function with some arguments pre-filled
def multiply(a, b):
    return a * b

double = functools.partial(multiply, 2)
print(f"Double of 5: {double(5)}")

Double of 5: 10

### `numpy` (Numerical Python)
This library adds support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. It's fundamental for scientific computing in Python.

In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(f"NumPy array: {arr}")

# Perform element-wise operations
print(f"Array multiplied by 2: {arr * 2}")
print(f"Sum of array elements: {np.sum(arr)}")

NumPy array: [1 2 3 4 5]
Array multiplied by 2: [ 2  4  6  8 10]
Sum of array elements: 15

### `pandas` (Python Data Analysis Library)
This library provides data structures (like DataFrames) and tools for data manipulation and analysis. It's widely used for handling tabular data. It allows reading and writing excel files and csv files.

In [ ]:
import pandas as pd

# Create a Pandas DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
print("Pandas DataFrame:")
display(df)

# Select a column
print("Ages column:")
display(df['Age'])

Pandas DataFrame:

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

Ages column:

0    25
1    30
2    35
Name: Age, dtype: int64